name: Deploy S3 Service

on:
  push:
    branches:
      - main

    paths:
      - 'flask-s3-service/**'
      - '.github/workflows/deploy-s3.yml'

  pull_request:
    branches:
      - main

    paths:
      - 'flask-s3-service/**'
      - '.github/workflows/deploy-s3.yml'

jobs:
  deploy-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t flask-s3-service \
            ./flask-s3-service

      # -------------------------
      # Install Snyk CLI
      # -------------------------
      - name: Install Snyk
        run: |
          npm install -g snyk

      # -------------------------
      # Authenticate Snyk
      # -------------------------
      - name: Authenticate Snyk
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}

      # -------------------------
      # Snyk Container Scan
      # -------------------------
      - name: Run Snyk Container Scan
        run: |
          snyk container test flask-s3-service:latest \
            --file=./flask-s3-service/Dockerfile \
            --severity-threshold=high \
            --exclude-base-image-vulns
            
      - name: Tag Docker Image
        run: |
          docker tag flask-s3-service:latest \
          255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/flask-s3-service:latest

      - name: Push Docker Image
        run: |
          docker push \
          255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/flask-s3-service:latest

      - name: Force ECS Redeployment
        run: |
          aws ecs update-service \
            --cluster ecs-exercise-cluster \
            --service s3-service \
            --force-new-deployment